services:

  frontend:
    build:
      context: ./frontend
    container_name: ecommerce-frontend
    ports:
      - "8083:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    container_name: ecommerce-backend
    environment:
      PORT: 3001

      DB_USER: appuser
      DB_HOST: postgres
      DB_DATABASE: ecommerce
      DB_PASSWORD: apppassword
      DB_PORT: 5432

      JWT_SECRET: change-this-later

      STRIPE_SECRET_KEY: pk_test_your_stripe_secret_key

      CLIENT_URL: http://localhost:8082

    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    container_name: ecommerce-postgres
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppassword
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./backend/database.sql:/docker-entrypoint-initdb.d/database.sql:ro

  redis:
    image: redis:7-alpine
    container_name: ecommerce-redis

volumes:
  postgres-data:
